services:
  web:
    container_name: app
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: >
      bash -c "uvicorn --host 0.0.0.0 --port ${PORT}  --reload app.main:app"
    volumes:
      - .:/code/

    env_file:
      - ./.env
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_SEEDS: "cassandra_db"
    volumes:
      - ./cassandra_data:/var/lib/cassandra


volumes:
  cassandra_data: